# Plugin configuration
---
plugins:
  cnrseng:
  - approve
  - assign
  - blunderbuss
  - cat
  - dog
  - help
  - heart
  - hold
  - label
  - lifecycle
  - size
  - lgtm
  - trigger
  - verify-owners
  - wip
  - yuks
  
  cnrseng/test-infra:
  - config-updater
  - override
  - project

# Enable config-updater for cnrseng/test-infra
config_updater:
    maps:
      config/prow/config.yaml:
        name: config
      config/prow/plugins.yaml:
        name: plugins
      config/jobs/**/*.yaml:
        name: job-config
      config/prow/labels.yaml:
        name: label-config

# Lower bounds in number of lines changed; XS is assumed to be zero
size:
  s:   10
  m:   30
  l:   100
  xl:  500
  xxl: 1000

# Additional labels for cnrseng
label:
  additional_labels:
    - tide/merge-method-merge
    - tide/merge-method-rebase
    - tide/merge-method-squash
