presubmits:
  cnrseng/test-infra:
  - name: presubmit-dummy
    branches:
    - master
    decorate: true
    always_run: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
